# Generated by Django 3.2.6 on 2021-12-15 13:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_alter_section_section_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='exam_asked',
        ),
        migrations.AddField(
            model_name='question',
            name='category',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to='home.category'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='question',
            name='topic',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='home.topic'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='question',
            name='lastUpdatedBy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.user'),
        ),
        migrations.AlterField(
            model_name='question',
            name='lastUpdatedOn',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
