# Generated by Django 3.2.6 on 2021-12-16 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_auto_20211215_1740'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='exam_ref',
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='explaination',
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
    ]
